server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ityouzi/aispringcloud.git
          search-paths: config
          username: 2504480136@qq.com
          password: ityouzi123456
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/